
fastapi >= 0.63.0
uvicorn >= 0.13.4
itsdangerous >= 1.1.0
Authlib >= 0.15.3
httpx >= 0.17.1
motor >= 2.4.0
python-decouple >= 3.4
dnspython >= 2.1.0
email-validator >= 1.1.2
jwt >= 1.2.0
PyJWT >= 2.0.1
python-multipart >= 0.0.5
mkdocs-material >= 7.1.3
python-dotenv >= 0.17.0
orjson >= 3.5.2
boto3 >= 1.17.66

